### ISSUE TITLE
Add unordered concurrent map

### ISSUE THREAD

**Issue by erezsh** [ebonnal/streamable#18]
When processing a sequence of items, we often want to get the results as soon as possible, without caring about the particular order (we can always enumerate first to recover the order later)

Python multiprocessing.Pool implements this with `imap_unordered` .

API options:

- Add a new `umap()` method
- Add an `ordered` boolean parameter to `map()` and `amap()`

I'm leaning towards the second option. It's more verbose, but easier to read, and removes confusion (e.g. should it be "aumap" or "uamap" etc.)

**Comment by ebonnal** [comment]
Neat approach, let's do that. If it's ok for you I am preparing the tests and changes and will co-author you in the PR and will ping you there for review 🙏🏻 !

**Comment by ebonnal** [comment]
⏫ @erezsh I let you check that it looks like what you had in mind 🙏🏻
