### ISSUE TITLE
How does it compare to other Python streaming libraries?

### ISSUE THREAD

**Issue by snth** [ebonnal/streamable#22]
Hi,

First off, this project looks really cool! I'm sorry to be starting with an issue asking for comparisons with similar projects but while I've long been a fan of stream processing type patters, I also want to limit how many projects I keep track off so it would be great to know how you see streamable viz a viz similar projects and where you want streamable to go in future?

Things in my current repertoire that look similar on the surface are:
* [streamz](https://streamz.readthedocs.io/en/latest/index.html)
* [RxPY](https://github.com/ReactiveX/RxPY)

**Comment by ebonnal** [comment]
Hello @snth ! Glad you came here

**Comment by ebonnal** [comment]
Hi @snth, happy to see you here, and great question!
(I'm not a power user of those libraries so correct me if I'm wrong!)

I will focus on differences on core design decisions, and how it guides how you shape your logic when you use each library:
- a `streamz`'s `Stream` instance is an acyclic tree of operations, root being source and leafs being sinks. `Stream.emit` allows to push an element through this tree down to every leaf.
- in `RxPY` implements an Observer Pattern: You compose operations to form a *subject*, onto which you can *subscribe* callback functions that will be notified/called when an incoming element has been operated and is ready for final consumption.
- `streamable`'s `Stream` is a decorator for iterables: i.e. a `Stream[T]` is initiated from an `Iterable[T]` and it is itself an `Iterable[T]`, and it exposes intuitive chainable lazy operations (stream's methods), each returning a new child `Stream[T]` (basically forming a linked list of operations). It is trivial to integrate as you can init a stream from any iterable in your codebase and throw it at any function accepting an iterable. To make the learning curve zero flat, I wanted it to be both pythonic and super close to how one manipulate collections in functional languages.

More comparison material: if you don't come from there you should check the [reddit post](https://www.reddit.com/r/Python/comments/1fp38jd/streamable_streamlike_manipulation_of_iterables/) (Especially the Comparison section at the end) and [this comment](https://www.reddit.com/r/Python/comments/1fp38jd/comment/lox4son/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

> where you want streamable to go in future?
I used its expressivity and seamless concurrency at my previous job to implement 30 custom ETL pipelines that are running in production for a year now. So I have the obvious responsability to maintain its quality over years. I put a lot of effort in designing the API to maximize intuitivity. It is now in the **feedback phase**, gathering some *"this would be a cool choice for my use case but it misses that feature"* or *"how to implement this use case?"*. Other contributors are starting to come into the loop, hopefully we can count you in too! 😄. I just hope that we can make it useful lib for everybody enjoying top-to-bottom-read iterable operations, out-of-the-box concurrency, and any other feature PRable 🤓. The only limit is that it must remain as unopinionated as possible, **this would be completely ouside of the philosophy of the library**:
```python
Stream.from_csv("sales.csv")
.join(db_type="postgres", db_name="main", schema_name="public", table="user", on_keys=("user_id",))
.to_bigquery("enriched_sales", partition=datetime.date.today(), batchsize=1024)
```
but one has to instantiate an iterable of rows using `csv` module, join in a `.map` using a `psycopg` client, and write in a `.foreach` using a `bigquery.Client.insert_rows_json` after batching rows using `.group(size=1024)`
